### ISSUE TITLE
Memory leak on QUIT

### ISSUE THREAD

**Issue by vegax87** [oragono/oragono#101]
I tried a small stress-test with this Python script that supports up to 512 irc connections.
Install: pip3 install pydle

```
import pydle

class CloneBot(pydle.Client):
    def on_connect(self):
         self.join('#test')
		 
		 
pool = pydle.ClientPool()
for i in range(511):
    client = CloneBot('MyBot' + str(i))
    pool.connect(client, 'localhost', 6667, tls=False, tls_verify=False)
	

pool.handle_forever()
```

After I closed this python script, I noticed an abnormal memory usage up to 100 times the initial output, something like 300MB+ RAM

**Comment by DanielOaks** [comment]
Hmm, I just tried pushing some new fixes on [devel+socket](https://github.com/DanielOaks/oragono/tree/devel%2Bsocket), any chance you could pull those changes and see whether you see the same issues? How about with that change plus your PR #102, how does that go?

I'm gonna do some additional testing here but would be very interested to see how those changes go.

**Comment by DanielOaks** [comment]
Alright I just did some rewriting of the socket code, moved it to a sending loop that makes more sense, times things out as appropriate and should help this memory usage stay relatively low (or at least let things go and get garbage-collected).

If you check with something like StackImpact, you should see the goroutines start low, jump as clients are added, and then go back to basically normal levels afterwards

**Comment by DanielOaks** [comment]
I think this should be fixed, though I'm not sure whether we need to do additional stuff to make sure the Client and relevant structs actually get deleted, or whether what we're doing currently with destroy should allow Go to GC it automatically.

Right now there's no trailing goroutines left behind from the clients themselves afaik (at least nowhere near as many), but StackImpact doesn't really show mem usage going down as much as I'd expect. Not sure whether that's just because the OS keeps the process on the memory open or because Go is still using and keeping that memory around for clients, but we should definitely take a closer look now that the first socket stuff is done.
