### ISSUE TITLE
make MONITOR per-session?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1053]
Right now, MONITOR operates at the client level, so rules added by one session will result in notifications sent to a different session.

It seems like client code will assume that MONITOR is per-session (e.g., that rules have to be re-added on every reconnection), so it would be better if Oragono implemented it at the session level as well.

**Comment by DanielOaks** [comment]
Hmm. Yeeeah it probably makes sense to do this. If MONITOR were used by end users then it'd make sense to e.g. persist it across the whole account but since it's mostly just client software transiently trying to check whether users they still have chat windows open for exist, per session makes a lot more sense.
