### ISSUE TITLE
send ERR_SUMMONDISABLED and ERR_USERSDISABLED?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1078]
@koraggknightwolf points out that we do not send these:

```
       445    ERR_SUMMONDISABLED
              ":SUMMON has been disabled"

         - Returned as a response to the SUMMON command.  MUST be
           returned by any server which doesn't implement it.

       446    ERR_USERSDISABLED
              ":USERS has been disabled"

         - Returned as a response to the USERS command.  MUST be
           returned by any server which does not implement it.
```

**Comment by DanielOaks** [comment]
`SUMMON` and `USERS` are weird really old commands designed around the assumption that users are accessing IRC locally and all that sorta junk. I'd rather not special-case those two commands just because a 20 year ago document said we MUST, clients will get the message either way. I think Insp also sends the unknown command numeric for at least summon when the module isn't loaded, but that's more of a side note and not a reason why I reckon we should leave our behaviour as-is.

**Comment by slingamn** [comment]
I checked the inspircd testnet and they send 445 and 446 in these cases. As discussed, I wouldn't mind sending these, it's sort of a cute easter egg :-)
