### ISSUE TITLE
should WHOIS leave the client idle?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1155]
r3m reports that other networks do not reset idle for `WHOIS`, but oragono does.

**Comment by slingamn** [comment]
Also `LIST` and `NAMES`?

**Comment by happyhater** [comment]
It must be all commands, excluding **/msg /notice /privmsg /say /me /ame /ctcp**

**Comment by slingamn** [comment]
If I understand the inspircd source correctly, idle is only reset for PRIVMSG and possibly NOTICE (and also they take care not to reset it for a CTCP reply).

**Comment by DanielOaks** [comment]
Totally makes sense to only update idle time on PRIVMSG, those are the only messages we can ensure the user behind the screen is sending themselves (NOTICE is typically for bot/automated replies, ctcp requests are user-sent but replies are automagically sent, so that'll get covered by having NOTICE leave the idle time alone)
