### ISSUE TITLE
dispatch web client doesn't work

### ISSUE THREAD

**Issue by prologic** [oragono/oragono#116]
Related: khlieng/dispatch#6

In testing dispatch silently doesn't want to play nice with Oragono and I haven't really had the time to figure out why yet.

**Comment by DanielOaks** [comment]
Hi, thanks for the issue! Oragono does use a strange casemapping but I
think that's the only real unusual thing that could cause this. I'll test
this out when I'm home and see what's up.

Any chance you'd be able to grab a packet capture of what goes on between
the client and server? Or enact `userinput` and `useroutput` logging and
post what comes out of Oragono? Thanks again for reporting the issue!

**Comment by DanielOaks** [comment]
Hmm... @prologic are you using the self-signed certs Oragono generates itself? I noticed that it connects fine if I don't use TLS/SSL but with TLS Dispatch just instantly disconnects (and tries reconnecting). Maybe Dispatch doesn't like the self-signed certs?

**Comment by DanielOaks** [comment]
I've tested this and it looks like this is the case. It also looks like there may be some confusion about InsecureSkipVerify on the Dispatch side, which is interesting. Thanks for reporting!

**Comment by prologic** [comment]
Yes I was using self-signed certs. I could go get some but this is just for home use for now so haven't bothered. Can we get Let's Encrypt support going for Dispatch? And/or can we add some config to skip verify self-signed certs?

**Comment by DanielOaks** [comment]
Hmm, strange (wrt that latest post in the Dispatch issue). If you're able to capture loclhost traffic with Wireshark or something similar, while SSL is disabled, I can dig into what's going on there as well.

The Let's Encrypt stuff would need to go for Oragono, but I'm not sure how to best integrate something like it into this natively. We could possibly have like an... `oragono le-certs` command that grabs/refreshes certificates with Let's Encrypt, but yeah. I think we'd need to have a good chat and map out exactly what commands should exist to do something like that, particularly since it involves setting up a local webserver and all too.

**Comment by prologic** [comment]
I think I already know partially what's going on. The default config is oragono is a bit too sensitive and its throttling my own connections in my local network haha we'll have to rethink the defaults maybe but for now I'm going to provide some configurability via the docker stuff

**Comment by prologic** [comment]
Btw if it helps I can probably share all the Docker stackfiles I have that would replicate my environment. I have real hw (*not that that matters*) but you could use some VMs of some kind. Docker machine itself is really just great for development but tbh I don't really use it!

**Comment by DanielOaks** [comment]
I think I'm alright with the defaults now, they've been extended a bit. If this issue pops up again I'll def help track it down!
