### ISSUE TITLE
oragono truncates last line of motd?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1167]
Unconfirmed report.

**Comment by DanielOaks** [comment]
Yeah the piece of code that loads the MOTD is a bit weird and complicated, in terms of how it reads the file. What's (probably) going on is that for the last line of the file (the one that's followed by no `\n`), an `EOF` error is returned and so the function breaks out before it can add that line. On *nix systems, since all their text editors always append an extra `\n` at the end it's not a problem but yeah. https://github.com/oragono/oragono/blob/79764cd549be5ac8e96971d9bda71a22b0d398f7/irc/server.go#L678

We could either modify that `loadMOTD` function to pay attention to the `EoF` or just make it instead read the whole file in at once and if a rogue `\n` is the last character then chop that off and keep loading.

**Comment by slingamn** [comment]
@mitaka8 confirmed this.
