### ISSUE TITLE
oragono self-dependency?

### ISSUE THREAD

**Issue by enckse** [oragono/oragono#117]
I just realized this and let me caveat with "I know enough go to be dangerous and package a go app in the AUR" :)

I feel like it is strange that oragono has itself as a dependency...could someone either clarify what build steps one would take to build locally themselves.

e.g. (sorry not testing each command here but am mostly interested in the ??? part)
```
git clone https://github.com/oragono
cd oragono
git checkout tags/v0.8.1
# assuming GOPATH is set
go get -v -d
# this downloads oragono master from github along with other dependencies...
make linux
```

if I do ^ that, I will actually get a build that has the 0.8.2-unreleased const in it because of the pull from oragono master for dependencies. You can see what I'm doing to overcome this in the aur for arch but I feel like I'm:
* Missing a go-ism for how to properly set the dependencies and/or managing them. I've googled as much as I can and read the docs and I feel like I'm either blind or...
* Hitting an unintended thing

**Comment by DanielOaks** [comment]
Oh I see. Yeah Go's a bit weird with versioning, since it just grabs the `master` branch without any way to get anything else from the looks of it.

What's going on with the above is that since `oragono` gets cloned to a place outside what Go expects, it doesn't actually know that you have the `github.com/oragono/oragono` package. Since the launcher (`oragono.go` in the root folder) uses the `github.com/oragono/oragono` package, the `go get` downloads that dependency. When you then build/run/etc `oragono.go`, it uses that newly-cloned package rather than the one you would expect.

In this specific case, right now I'd probably handle it how the AUR package does, i.e.:

1. `go get github.com/oragono/oragono`
2. `cd $GOPATH/src/github.com/oragono/oragono/`
3. `git checkout v0.8.1`
4. `git submodule update --init` (this gets the latest packaged versions of dependencies when this version of Oragono was released – otherwise you could probably do the `go get` above if you really wanted to but there's a slight possibility things could be a touch broken if our dependencies aren't careful).
5. `make linux`

With that you should be right every time. It could be good to look at this more properly sometime though. The way I'm currently approaching it is mostly "If you want a stable build, download the release (or download the src and switch to the latest tag), if you want the latest code then just `go get` the repo"... but that might not be the best way to go. Any thoughts on your side, being the packager and all? :)

**Comment by enckse** [comment]
using the best AUR best practices and what you suggested/changes I think I have an approach that at least makes some logical sense:
1. aur clone oragono & oragono-vendor (AUR-ism)
2. link oragono.vendor -> oragono-vendor (AUR-ism) and update (which gets the current vendor versions)
3. set GOPATH (go-ism)
4. **ok here we go** symbolic link the aur cloned oragono into the vendors/github.com/oragono/<path>/mkcerts|irc so that go can resolve that as a vendor package (go-ism, I'm reaching...I know)
5. make linux

I would say this feels wonky (mainly step 4) but I think it is following the guiding principles between AUR packaging and golang and unless @DanielOaks plans to chase restructuring dependencies entirely it should be relatively stable and/or break for logical reasons and not just be compiling random versions of things.

@DanielOaks - if you want to close this at this time and re-visit if you ever see fit, feel free. I think I understand the components now enough that if I do bump into future problems it will be general changes and not a lack of understanding.

**Comment by enckse** [comment]
I think this ticket is safe to close (I've had no issues keeping the arch AUR package up-to-date)

**Comment by DanielOaks** [comment]
Ah, awesome to hear! Thanks a bunch for doing that by the way. I know I've been a bit slack on updating the website RSS feed in the past so I'll try to get on top of that as well, note the process in the release process docs and all :)
