### ISSUE TITLE
implement leaf and hub

### ISSUE THREAD

**Issue by happyhater** [oragono/oragono#1265]
Hello,

What do you think about implementing leaf/hub, to *relay* multiple servers ?

**Comment by slingamn** [comment]
This is something we've been considering, yeah (it came up in connection with #1000). Roughly speaking, the hub node would own all `Client` objects, be authoritative about channel memberships, own the database, etc., and the leaf nodes would own the `Session` objects.

But we haven't started work on this at all because it's major surgery.

**Comment by slingamn** [comment]
The other major unanswered question is how to manage the leaves for high availability. It's tempting to do the whole thing in kubernetes (where the leaves are "cattle" and the hub is a "pet") but I don't have a good sense of how the pieces are going to fit together.

**Comment by slingamn** [comment]
Closing in favor of #1532
