### ISSUE TITLE
reevaluate error responses for SANICK

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1277]
@eskimo reported client issues with SANICK. Part of the problem is that SANICK sends `433 ERR_NICKNAMEINUSE` to the originating client (as opposed to the target) on failures; these were then being misinterpreted by the client, causing the client to change its *own* nickname.

Let's see what other SVSNICK/SANICK implementations are doing here.

**Comment by jwheare** [comment]
We use ERR_NICKNAMEINUSE to prompt the client to choose a different nick for themselves, which we then submit as NICK, so yes this is incorrect behaviour. You shouldn't send this to either the target or originating client.

**Comment by slingamn** [comment]
Any suggestions on what we should send?

**Comment by jwheare** [comment]
SANICK is non-standard, maybe send a NOTICE if you want to send something. Or a FAIL SANICK...

**Comment by jwheare** [comment]
As long as you're not too bothered with back-compat.

**Comment by eskimo** [comment]
Looks like I can't reply to the thread on the inspircd repo, but I don't see a problem with sending the messages as you suggested @slingamn. Most clients throw messages they don't know into the status window and most users know to look at the status window for something they didn't see a response for. However, a NOTICE is probably a better option since most clients will show them either in the channel the user is currently viewing rather than having someone hunt it down and eventually find it in a status window.
