### ISSUE TITLE
disallow overbroad bans?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1311]
See #972. @mogad0n reported a channel operator who did `/kb some_nick`, resulting in a ban on `*!~user@example.com`, where example.com is the server name --- i.e., a ban on all always-on clients. This should possibly be disallowed.

**Comment by slingamn** [comment]
I've also thought about a `BAN` command in this regard: you do `/ban add some_nick` or `/quote ban add some_nick` and Oragono generates the appropriate ban (either `*!*@host` for anonymous or `account!*@*` for authed).

**Comment by DanielOaks** [comment]
Maybe for always-on clients we could just set their hostname to the accountname or some variation of it, similar to how cloaks work on freenode/etc (e.g. `unaffiliated/dan`). We might be able to use `alwayson/dan` or something else? That'd probably let the bans work as intended without any changes from clients.

If we do create a `BAN` command I'd mostly be wondering how much it'd be used, since `/kb` and similar commands (even via the gui) already get provided by the client themselves and it seems like people are used to 'em.

**Comment by slingamn** [comment]
#1312
