### ISSUE TITLE
force-nick-equals-account and login-via-pass not working correctly?

### ISSUE THREAD

**Issue by Mystara2002** [oragono/oragono#1319]
Howdy,

I've set "force-nick-equals-account: false" in my configuration, but having registered an account when I try to use /nick Test, I get the error:

"[11:54:43] NICK You must use your account name as your nickname"

Under "nick-reservation:" I've also tried setting "enabled: false" but this also has no effect.

I've completely killed and restarted the ircd after making these changes with no effect.  I've also tried deleting the ircd.db file, but this also doesn't help.

In a possibly related bug, if I join using a different nickname and then attempt to identify to nickserv, I get the error:

"Authentication failed: Your nickname must match your account name; try logging out and logging back in with SASL"

This is despite the fact that under "require-sasl:", I have "enabled: false".

Another possibility would be the /pass command, since I have "login-via-pass-command: true" set.  However, when I try that, I get:

"462:  | [0] Blah, [1] You may not reregister"

Which is odd, because I'm not registered.

Anyway, since I have user persistency enabled by default, the consequence of this is that for a user on an older client, when the user registers their nickname they can no longer access it.  Oragono appears to set an impossible condition in which the user must have the username to identify, but cannot take the username because it is taken by a persistent user.  

(oragono-2.3.0)

**Comment by Mystara2002** [comment]
Okay, I see from the code that if your account is persistent then it's equivalent to nick-reservation being set to 'true'.
That still raises the question of how you retrieve an account if you have a persistent account without SASL.  I shall continue my investigation.

**Comment by slingamn** [comment]
Due to the age of the protocol, there's an unfortunate ambiguity in the terminology here: depending on context, "registered" can refer either to ["connection registration"](https://tools.ietf.org/html/rfc2812#section-3.1) (the initial `NICK` and `USER` handshake that is required to connect to IRC, receive `001 RPL_WELCOME` etc.) or to account registration. The `462 ERR_ALREADYREGISTRED` [sic] numeric refers to the first sense of the term.

The correct workaround for this is in fact `login-via-pass-command`, but the `PASS` command must be sent as part of the initial `NICK` and `USER` handshake --- this is how legacy clients generally interpret a server password field. If the client sends, e.g., `PASS mystara:hunter2` (where `mystara` is the account name and `hunter2` is the account password) in the initial part of the handshake, this should be interpreted correctly and attach your client to the "always-on" or "persistent" presence for the account. What client is this, by the way?

**Comment by Mystara2002** [comment]
It was the mibbit widget, which doesn't allow the insertion of a password.  A user was using something else, but they haven't told me what the client was.

Could there perhaps be an option to take over a persistent presence post-connection?  Something akin to a killing of the persistent presence followed by a nickname change to the (now removed) persistent presence?

**Comment by slingamn** [comment]
I'll consider it --- I'm not sure how much additional implementation complexity is involved.

I think the current recommended workaround for individual users who can't supply a password during connection registration (either via SASL or PASS) would be to disable always-on (`/msg nickserv set always-on false`), then connect using a temporary nickname and then use `/msg nickserv identify`. The problem is that to do this, they have to be logged into their account already, so it'll only work on the first connection. I should think more about this.

In passing:

1. I'd recommend [Kiwi](https://github.com/kiwiirc/kiwiirc) as a mibbit replacement; the new version is just static files that talk to an Oragono websocket. We have [example config files](https://github.com/oragono/testnet.oragono.io) that we use on our testnet.
2. I'd also recommend `force-nick-equals-account: true`; among other things, it ensures that someone successfully identifying with `/msg nickserv identify` will automatically have their nick changed.

**Comment by slingamn** [comment]
This came up again on #1336; the discussion there has some reasons why this is hard to do.
