### ISSUE TITLE
NickServ cannot login users after connection if guest prefix is ON

### ISSUE THREAD

**Issue by Amiga60077** [oragono/oragono#1336]
When you register a nickname, you have to login via the PASS command (ie. pre-connection), eg. PASS,NICK,USER authentication process, as if you join then try to ID, it gives you the following message,
-NickServ- Authentication failed: Your nickname must match your account name; try logging out and logging back in with SASL

Basically /NickServ Identify <account> <pass> - Does not work if Guest Prefix is enabled in the config file

**Comment by slingamn** [comment]
Thanks for the report!

With `force-guest-format: true` and `always-on: opt-in`, I can't reproduce this against 2.3.0 or master. Are you also using `always-on: opt-out` or `always-on: mandatory`? In this case, that error will be produced because there's an existing client (the always-on client) using that nickname.

**Comment by Amiga60077** [comment]
my force-guest-format is true, and always-on mandatory - I am also using the guest-nickname-format "$*" - which is shorter than the original "Guest_" prefix which was specified there (I did originally try prefixing with "!*" but it would not allow the ! symbol

**Comment by slingamn** [comment]
Yeah, this is caused by `always-on: mandatory`, not by `force-guest-format: true`. The error message is a little confusing. But you can't log into an always-on client after registration, you have to use SASL or `PASS`.

**Comment by Amiga60077** [comment]
I really do not understand why its prohibited to login after connection, unless I am missing something here

For example if configured properly (Unreal+Anope) both allow PASS nick:pass login and also the /NS ID login methods, so I really dont know why Oragono prevents login after connect, some clients/bots have not been coded to provide PASS on connection, and to the novice, it would be hard to enable that functionality, when a simple /NS ID after login would work wonders for them users. - Just my 2 cents anyway, Thanks

**Comment by slingamn** [comment]
It's an architectural problem. With always-on, the client is considered to already exist from the time that the server is started, even without any connections. For example, it can already receive direct messages, be joined to channels (whichever channels it was joined to before restart), etc. (And it will continue to do so even if all the connections are closed.)

The problem with allowing a fully connected client to `/ns identify` into an always-on client is that we would either have to "merge" the two clients (e.g., combining their channel memberships), or fully tear down the anonymous client (probably by sending a QUIT for its nickname, possibly some other magic) in order to transfer it. This would add implementation complexity.

Again, we support `/nickserv identify`, just not when there's already an always-on client for the account.

**Comment by Amiga60077** [comment]
Yeah I now see, because its basically acting like a BNC - in which you DO need to specify the BNC nick and pass in the connection PASS command on connection for, Now it makes sense

Thanks for the clarification :)
