### ISSUE TITLE
remove vhost request system?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1346]
Just throwing this up for discussion: I'd kind of like to remove the vhost request queue system. It adds a lot of complexity and doesn't seem to be very useful, especially given that IP cloaking is the default now.

**Comment by Amiga60077** [comment]
Yes that would be good, besides that anyone can just request a vhost by asking network staff surely, it doesnt need its own services-based request system

**Comment by slingamn** [comment]
@DanielOaks thoughts on this?

**Comment by DanielOaks** [comment]
Eh I don't mind removing this too much. It's useful for a very specific type of large network, to more easily let a vhost group approve vhost requests whenever instead of directly chatting with users. But I don't mind just recommending setting up a `#help` channel or something users can join and just ask, like how freenode does it. Make sure you remove the [user-requests section in the config files](https://github.com/oragono/oragono/blob/master/conventional.yaml#L479) as well~
