### ISSUE TITLE
defer +u snomasks until the end of connection registration

### ISSUE THREAD

**Issue by eskimo** [oragono/oragono#1396]
Upon connecting it seems the sent NOTICE is as follows:
`:iglooirc.com NOTICE jexxley :14-ACCOUNT14- Client 14[*14] logged into account 14[eskimo14]`

When it should've been:
`:iglooirc.com NOTICE jexxley :14-ACCOUNT14- Client 14[esk1mo14] logged into account 14[eskimo14]`

**Comment by slingamn** [comment]
This is awkward. This is a login with SASL (or with the PASS-stuffing technique), which occurs before connection registration (i.e., before `CAP END`, or before both `NICK` and `USER` have been sent in the absence of capability negotiation).

The problem is that the client is being logged into the account, but doesn't actually have a nick yet. They may not have sent `NICK` at all. Even if they have sent `NICK`, that nick hasn't actually been validated for their ability to claim it --- it could belong to an entirely different client --- so it would be inappropriate to reference it in the sno line.

**Comment by eskimo** [comment]
This is not the case. The messages sent are as follows for the connecting client:
```
<< CAP LS
<< NICK jexxley
<< PASS [REDACTED]
<< USER jexxley 0 * :jexxley@iglooirc.com
<< CAP REQ :sasl
<< AUTHENTICATE PLAIN
<< AUTHENTICATE [REDACTED]
<< CAP END
```

**Comment by slingamn** [comment]
Registration doesn't complete until `CAP END` is sent.

**Comment by eskimo** [comment]
But you can't SASL after CAP END is sent?

**Comment by slingamn** [comment]
Technically you can, but it's definitely preferable to do it before registration (in particular it is required if you want to use the multiclient features).

But either way, while registration is taking place, the client doesn't have a nick. We could try deferring the snomask until the end of registration?

**Comment by slingamn** [comment]
(But also, snomasks are kind of bad in general; they're no longer enabled in the recommended default configuration.)

**Comment by eskimo** [comment]
Yeah I suppose waiting until the end would be better than sending a notice that * logged into an account. 

I don't necessarily use the account login for anything (just happened to see error parsing) but figured I'd report it.
