### ISSUE TITLE
manually created [dk]lines with an expiration are never deleted from the datastore

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#144]
d-lines are written to, and deleted from, the datastore by the `/dline` and `/undline` commands. Expiration is handled by `CheckIP`, which currently doesn't know how to modify the datastore, only the in-memory representation. Therefore, any manually created d-line with an expiration date will never be deleted from the datastore.

The throttler automatically creates d-lines with a 15-minute expiration; these are never written to the datastore at all, so they get cleaned up automatically by `CheckIP`.

Possible fixes:

1. Tell `CheckIP` how to delete expired d-lines from the datastore. This complicates the lock model somewhat.
2. Don't write any d-lines with expiration dates to the datastore in the first place. This is easy, but if people are setting temporary d-lines on a timescale of a week or more, they probably expect them to persist across restarts.

(This applies to k-lines as well.)

**Comment by DanielOaks** [comment]
Hmm... Yeah in that case we should do something around letting CheckIP delete expired dlines, keeping around the non-throttling ones between restarts makes sense (also makes sense to drop the throttle dlines between restarts, since when the server comes back up everyone is gonna try to reconnect). With regards to the klines, maybe we could have a task that runs every now-and-then (or maybe just every time a new kline is added) that checks whether there are any old ones and deletes them from the db?

**Comment by slingamn** [comment]
I noticed that buntdb has an auto-expiration feature: https://github.com/tidwall/buntdb#data-expiration

**Comment by DanielOaks** [comment]
Ooh, that's cool

**Comment by slingamn** [comment]
We should refactor the (de)serialization code as part of this; right now it's split between `[DK]LineManager` and the handler code in `irc/handlers.go`.

**Comment by slingamn** [comment]
Fixed in #329
