### ISSUE TITLE
RELAYMSG identifiers should respect bans/mutes?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1502]
Right now, RELAYMSG bypasses all channel ban/mutes, but we could enforce them against the spoofed relay nicks (there might be some subtleties with casefolding around the separator char). See also #1441.

**Comment by mogad0n** [comment]
This would be quite useful for me because I have stopped relying on stateful bridges completely. While I agree about "moderate from the other side", certain channel operators may not have permissions synchronized and also things like IRC has the most elaborate bots and that can be used for spam and adding ignores for this is slightly difficult for the uninitiated.

Would there be an issue with having a `/` in the nick being relayed. `mo/gad0n/discord` is what would show up? Also it is ridiculously easy to change your nick on many of these platforms can you rapidly evade by switching your nick when a `MUTE` is applied. I am unsure if  #1441 is relevant to what I am asking.
