### ISSUE TITLE
define lock model and bring existing mutexes into compliance with it

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#152]
Rough idea: define 3 tiers of locks, tier 1 being the "innermost" (protecting getters and setters), tier 2 being, e.g., the kind of mutex that's attached to `MonitorManager` (protecting some non-atomic state of its own, but needing access to fields on `Client` and `Server` that themselves require synchronization), and tier 3 being the "outermost" (protecting large operations like rehashing from stepping on themselves). While holding a lock, you can only acquire a lock of *strictly* higher tier (this is therefore a strict partial order, rather than a total order). The locks protecting `Socket.Write` and `logger.Manager.Log` are considered level 1. The read-write mutex protecting DB transactions is considered either level 1 or 2, TBD.

Mutexes in master that need to be reviewed and brought into compliance:

- [x] `Channel.membersMutex`: currently somewhere between tier-2 (protecting macroscopic operations on the channel) and tier-1 (protecting individual members of the channel)
- [x] `Client.destroyMutex`: this is more or less a good example of a tier-3 mutex, needs a looking-over though
- [x] `Client.quitMutex`: this is a candidate for elimination (maybe it can be folded into one of the other `Client` mutexes?)
- [x] `Client.timerMutex`: this is a candidate for factoring out into a separate object with its own synchronization (maybe even using golang channels?)
- [x] `Server.channelJoinPartMutex`: I was unhappy about this one before I understood how I/O works in Oragono (tl;dr `irc/socket.go` buffers all sends in userspace, so sending never blocks the current goroutine). This is probably a decent example of a tier-3 mutex. It might make sense to factor out into a `ChannelManager` object.
- [x] `Server.registeredChannelsMutex`: this one is hard. It can possibly become an inner mutex of the `ChannelManager`. We could maybe use a golang channel here to asynchronously persist a "log" of actions to the db?

Other tasks:

- [ ] Document all of this in `DEVELOPING.md`

**Comment by DanielOaks** [comment]
For sure, this makes a lot of sense.

What's your thoughts on the `Serverr.configurableStateMutex` that `REHASH` currently uses to protect the elements it touches? Move away from that and towards a bunch of tier 1 mutexes instead, moving most of the elements it updates to getters and keeping the tier 3 `Server.rehashMutex`?

Just a note to myself as well: the `PROXY` and `WEBIRC` stuff needs to be protected by mutexes as well, since right now they aren't.

**Comment by slingamn** [comment]
Good point. `Server.configurableStateMutex` should currently be in compliance with tier 1. I think once we start adding getters for mutable fields that is not "configurable" (in the sense of being modified only by rehash), we can rename it to `stateMutex` and use it to protect those fields as well.

In general I think I prefer to have only a single tier 1 mutex per structure, with the understanding that it can only be held for very brief periods of time (basically for Go's equivalent of a `memcpy` call), rather than multiple mutexes with distinct purposes. This should hopefully make it harder to write deadlocks or long critical sections that can cause contention.

**Comment by DanielOaks** [comment]
Sounds good, and yeah only having one mutex per structure sounds good.

I am a little wary on having broad mutexes on Server (since they're used all over the place) but honestly it shouldn't be a huge issue. I've got some stress-testing stuff [here](https://github.com/DanielOaks/irc-stress-test) which we can use to test differences between broader and narrower mutexes down the line anyways I'm happy to go ahead with it as you've described!

**Comment by slingamn** [comment]
The stress tester is totally neat --- once more of the lock model is implemented, we should use it with the race detector as a way of looking for data races.

**Comment by DanielOaks** [comment]
Hmm, are we good to document this in DEVELOPING.go? Based on the checklist at least it looks like most of our locks comply with the new model.

**Comment by DanielOaks** [comment]
With #168, this should be completed! Thanks a bunch @slingamn, these were some much-needed changes and really help clean everything up :)
