### ISSUE TITLE
halfops should be able to change the channel topic

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1523]
The permissions of halfops are currently undocumented. Let's give them the ability to do topic changes, then document the resulting set of permissions (granting and removing voice, kicking, and changing channel topics).

**Comment by Mikaela** [comment]
Are founders and admins documented? How about ops (in case of new IRC users)?

**Comment by DanielOaks** [comment]
Eh, in terms of other ircds the permissions of halfops are a bit flexible anyways iirc, so I'm happy enough to do this because it feels like something halfops should be able to do anyway. For us specifically, I don't think we have any specific documentation around this (Channel Operators guide mayhaps? :P)

**Comment by slingamn** [comment]
This is covered here:

https://github.com/oragono/oragono/blob/1fad76b906d672d6f1a90949581febe506ada504/docs/MANUAL.md#channel-prefixes

but we should copy it into the user guide once it's fixed up, probably.
