### ISSUE TITLE
rethink message truncation

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1577]
In connection with #1575 and https://github.com/goshuirc/irc-go/pull/45, @kylef really made me rethink the whole idea of message truncation. Truncation can completely change the meaning of a message, even for English encoded in ASCII. (It could cut off a clause starting with `, unless` or `, except`; I'm sure there are more colorful examples.)

Why truncate messages? As the server, we're equipped to predict the exact size of the relayed message and preemptively reject PRIVMSG or NOTICE if they would exceed the limit (as indeed we do for TAGMSG, by enforcing the 4094-byte limit and sending `ERR_INPUTTOOLONG`).

The question is, what error would we send? This is a case where a cap to choose between standard replies and legacy NOTICE would be relevant: we would prefer to send a standard reply but we also want this to display adequately in legacy clients.

**Comment by slingamn** [comment]
The numerics registry describes `417 ERR_INPUTTOOLONG` as being used by ircu to handle the old-fashioned 512-byte limit, before there were tags.

**Comment by DanielOaks** [comment]
I wouldn't mind trying it out so long as there's a way to go back to silent truncation in the config file and we give it a gooood test with real clients before releasing it as the default.

`ERR_INPUTTOOLONG` could work, but I could also see clients not really wanting to adjust their truncation behaviour and re-submit messages based on that numeric (given its use as like "you screwed up tag output!" and all). I don't wanna define new numerics if at all possible, maybe we could just throw a `FAIL` back at the client, and/or with a cap that switches between a server-sent notice and a `FAIL` notifying them about it if we really, really feel like doing that.

I mentioned this in the channel but will mention it again here. Clients that aren't as conservative with how long each message could be may have trouble when they send messages that get split across multiple privmsgs because e.g. a user types a 550-char message, client splits into one 450char and one 100chat message, 450char gets rejected for ^ reasons and 100char then goes through fine. Unless user's paying attention they'll have zero clue what was missed out or sent successfully. In the error message, we should always include a snippet to let them know which message was screwed and not sent (X characters from start of the message, etc).

**Comment by slingamn** [comment]
I'm probably going to leave these debug lines in 2.6; I'll remove them in 2.7.
