### ISSUE TITLE
UBAN Enhancement suggestions: suspend dms and ban ips associated with a domain name.

### ISSUE THREAD

**Issue by mogad0n** [oragono/oragono#1583]
Suspend ability to send dms and additionally all ranges publicly associated with a particular domain name  

It can be added as an additional parameter to the `/uban add` command. I recall the discussion moving on to how tedious the `/uban add` command is getting with the addition of new features, so that's a potential drawback (I mentioned flags here).

Also possibly,
adding ISPs like (just as examples): linode.com  .. We spoke a bit about this https://lsd25.dev/gzavx

**Comment by slingamn** [comment]
Two orthogonal issues here, really:

1. Adding a new "soft UBAN" type, comparable to require-sasl, that prevents affected users from sending DMs
2. Making this new soft UBAN type work with KLINE (i.e., the NUH-mask functionality of UBAN) as well as DLINE

I'm more interested in (1) than in (2) because of my sense that RDNS is of limited use as a mitigation here; in general, you should be able to identify the affected CIDR and ban it.

**Comment by DanielOaks** [comment]
I'm pretty sure other ircds have these sorta 'quarantine' commands that stop users from sending messages and junk like that, probably worth looking at what they do. `UBAN` is getting big and we should stop it from getting so big that it's a mess.

**Comment by mogad0n** [comment]
So wrt  (1) i.e. the ability to prevent someone from sending dm's you guys are onboard?
`UBAN` will become very complicated so idk why we don't use flags to make it short.. `REQUIRE-SASL` is too much but that's a different topic.

(2) is not favorable to you folks yeah? 

just commenting so that this issue isn't just lying around and you can make decisions.
