### ISSUE TITLE
corrupted buntdb database

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1603]
We got a report that Oragono failed to start after a server reboot:

```
Mar 26 10:06:34 redacted oragono[4187]: 2021-03-26T08:06:34.910Z : error : server     : Could not load server: Failed to open datastore: invalid database
```

This error is produced directly from buntdb on failure to load the file. It may be an instance of https://github.com/tidwall/buntdb/issues/71 ; I'm trying to get logs from the operator to see if it was a dirty shutdown.

**Comment by Mikaela** [comment]
The IPs are carrier grade NAT and localhost so I don't bother redacting myself.

```
Mar 26 09:30:43 silta oragono[2894987]: 2021-03-26T07:30:43.973Z : info  : connect    : Client connected [MikaelaSuomalainen] [u:~u] [r:Mikaela Suomalainen <mikaela.suomalainen@piraa>
Mar 26 09:41:52 silta oragono[2894987]: 2021-03-26T07:41:52.517Z : info  : connect-ip : disconnecting session of MikaelaSuomalainen from 85.76.33.43
Mar 26 09:42:12 silta oragono[2894987]: 2021-03-26T07:42:12.579Z : info  : connect-ip : disconnecting session of MI1 from 127.0.0.1
Mar 26 09:42:49 silta systemd[1]: Stopping oragono...
Mar 26 09:42:50 silta oragono[2894987]: 2021-03-26T07:42:50.521Z : info  : server     : Oragono v2.5.1 exiting
Mar 26 09:42:50 silta systemd[1]: oragono.service: Succeeded.
Mar 26 09:42:50 silta systemd[1]: Stopped oragono.
-- Reboot --
Mar 26 09:43:14 silta systemd[1]: Started oragono.
Mar 26 09:43:14 silta oragono[1110]: 2021-03-26T07:43:14.851Z : info  : server     : oragono-2.5.1 starting
Mar 26 09:43:14 silta oragono[1110]: 2021-03-26T07:43:14.852Z : info  : server     : Using config file : /home/oragono/oragono-conf/ircd.yaml
Mar 26 09:43:14 silta oragono[1110]: 2021-03-26T07:43:14.853Z : info  : server     : Using datastore : ircd.db
Mar 26 09:43:14 silta oragono[1110]: 2021-03-26T07:43:14.940Z : error : server     : Could not load server: Failed to open datastore: invalid database
Mar 26 09:43:14 silta systemd[1]: oragono.service: Main process exited, code=exited, status=1/FAILURE
Mar 26 09:43:14 silta systemd[1]: oragono.service: Failed with result 'exit-code'.
Mar 26 09:43:15 silta systemd[1]: oragono.service: Scheduled restart job, restart counter is at 1.
Mar 26 09:43:15 silta systemd[1]: Stopped oragono.
Mar 26 09:43:15 silta systemd[1]: Started oragono.
Mar 26 09:43:15 silta oragono[1259]: 2021-03-26T07:43:15.601Z : info  : server     : oragono-2.5.1 starting
Mar 26 09:43:15 silta oragono[1259]: 2021-03-26T07:43:15.602Z : info  : server     : Using config file : /home/oragono/oragono-conf/ircd.yaml
Mar 26 09:43:15 silta oragono[1259]: 2021-03-26T07:43:15.602Z : info  : server     : Using datastore : ircd.db
Mar 26 09:43:15 silta oragono[1259]: 2021-03-26T07:43:15.691Z : error : server     : Could not load server: Failed to open datastore: invalid database
Mar 26 09:43:15 silta systemd[1]: oragono.service: Main process exited, code=exited, status=1/FAILURE
Mar 26 09:43:15 silta systemd[1]: oragono.service: Failed with result 'exit-code'.
Mar 26 09:43:15 silta systemd[1]: oragono.service: Scheduled restart job, restart counter is at 2.
Mar 26 09:43:15 silta systemd[1]: Stopped oragono.
Mar 26 09:43:15 silta systemd[1]: Started oragono.
Mar 26 09:43:16 silta oragono[1306]: 2021-03-26T07:43:16.152Z : info  : server     : oragono-2.5.1 starting
Mar 26 09:43:16 silta oragono[1306]: 2021-03-26T07:43:16.152Z : info  : server     : Using config file : /home/oragono/oragono-conf/ircd.yaml
Mar 26 09:43:16 silta oragono[1306]: 2021-03-26T07:43:16.152Z : info  : server     : Using datastore : ircd.db
Mar 26 09:43:16 silta oragono[1306]: 2021-03-26T07:43:16.328Z : error : server     : Could not load server: Failed to open datastore: invalid database
Mar 26 09:43:16 silta systemd[1]: oragono.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by slingamn** [comment]
This certainly appears to be a clean shutdown on our side, so there should have been a `fsync(2)` before the stop at `2021-03-26T07:42:50.521Z`. This points away from it being a truncation issue.

**Comment by DanielOaks** [comment]
Okay this is strange. In two cases in the db, the 'command' has the last ~20-100 characters cut off the end, has no `\r\n`, and the next command just starts right away. It's not an instance of that buntdb issue linked above because the file itself is fine, both these instances happen in the middle of regular data (towards the end of the db file though).

**Comment by DanielOaks** [comment]
Reported to the buntdb repo, this looks pretty strange and tidwall would probably have a better idea of where to start searching for the cause of this, or what the most likely cause could be.

**Comment by DanielOaks** [comment]
Hmm, they think it's probably multiple processes writing to the db at the same time and causing something strange there. I don't think that specifically's the case - Ora falls over if it can't attach to the listening socket (at least it does on windows, need to confirm it also dies on linux in the same situation), and if that happens then it can't get any clients connected and so couldn't start writing any keys.

I wonder if maaaaybe:

1. Ora1 has buntdb opened.
2. Ora1 starts writing the key to the db.
3. Ora2 gets started and opens the database file (since I think that's the first thing Ora does?).
4. Ora1's write gets interrupted.
5. Ora2 dies because it can't attach to the listening socket.

If Ora2 opening the db file causes writes-in-progress to die that could be causing this sort of corruption. Still feels weird and like enough of a race condition that I'd be reeeally surprised to see it twice in a single db, but races are weird. If this is what's going on, we should lock (try to open the listener sockets) before we start up the database, that'd prevent this.

Otherwise, our assumption falls back to buntdb weirdness. I might not mind doing a bit of stress-testing in this kind of direction regardless (have a few separate threads all writing to the db in tight loops) anyway, just to make us more sure about it, but yeah from a cursory look it feels like bunt's doing its locking pretty properly.

**Comment by slingamn** [comment]
We intentionally open the listeners last so that, e.g., account registrations are fully loaded before we accept any incoming connections. If we're going this route we could probably pull in a flock library, e.g., https://github.com/gofrs/flock

I'm somewhat skeptical of the double-start explanation because I don't think systemd would start the process twice, and if it did we would probably see some indication of it in the systemd journal.

**Comment by slingamn** [comment]
It seems to me if that if this were a case of writes getting interleaved, the missing half of the write would appear later in the file, possibly in the middle of another value. But it looks like this didn't happen? (It might be hard to see.)

**Comment by slingamn** [comment]
The remaining part of that split value would presumably be `5:29:32.572548859Z`

**Comment by DanielOaks** [comment]
Yeah there's zero extra inserted data, so interleaved writing didn't happen here. The only candidate along that line is that a write was halfway through, another process opened the file and interrupted that write-in-progress and then the original writer continued silently from there. Since there's no extra inserted data, just adding the missing end portion to the end of both the values makes the db load fine, no dramas.

What you've said about systemd opening it twice is totally fair, it'd be really _nice_ if that was what went on but it feels a little bit unlikely unfortunately. I dunno, honestly I feel like some stress testing of the lib might be the thing that gives us more data to go on here, but yeah not sure.

**Comment by slingamn** [comment]
I'm pretty confident in the attribution of this to `ENOSPC`; closing, since we have an upstream buntdb fix for that case.
