### ISSUE TITLE
Whitelist a banned IP

### ISSUE THREAD

**Issue by matheusfillipe** [oragono/oragono#1604]
I am running some experiments spawning multiple bots from the same machine (yes.. haha). Those are tests. I am getting this message from time to time after disconecting them all and reconecting:
```
ERROR :You are banned from this server (You have attempted to connect too many times within a short duration. Wait a while, and you will be able to connect.) [8m53s]

```

Is there a way to whitelist my ip for this or this is hardcoded?

**Comment by DanielOaks** [comment]
Hey Matheus!

By default we should whitelist localhost, so that sounds a bit strange. But
it should be a simple fix, just add the IP that Oragono's seeing those
connections as to the ip-limits->exempted list, and those connections won't
be banned for violating the limits anymore!

The specific part of the config file is this list here
<https://github.com/oragono/oragono/blob/master/default.yaml#L266>, give us
a shout if you have any trouble.

**Comment by slingamn** [comment]
+1, this should be unproblematic if you follow the usual procedure for config changes (edit the file, save it, and then rehash):

https://github.com/oragono/oragono/blob/master/docs/MANUAL.md#rehashing
