### ISSUE TITLE
allow setting the minimum TLS version

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1611]
Go supports the following versions:

```
    VersionTLS10 = 0x0301
    VersionTLS11 = 0x0302
    VersionTLS12 = 0x0303
    VersionTLS13 = 0x0304
```

`(tls.Config).MinVersion` can be used to set the minimum version, which defaults to 1.0. Operators may want to increase this.

**Comment by DanielOaks** [comment]
I'll say that I absolutely hate configuration of security things like this, but so long as it's for the purpose of letting people kill older versions of TLS it'd be fine I guess. Let's please not bundle any other sort of configuration of ciphers or other esoteric specifics in with this.

**Comment by ChrisTX** [comment]
I wouldn't suggest making ciphers configurable, and TLS 1.3 uses completely different cipher names. There is a point that OpenSSL and with that nginx don't directly expose them because there are no insecure ciphers in 1.3. It shouldn't need configuration.
However, the reason I brought this up is that gotls enables 1.0/1.1, which are to some extend insecure (they use CBC modes only and HMAC-SHA1 and so on) by default and disabling this is quite valid, and should maybe even be the default.

As for ciphers with 1.2, gotls enables AES-CBC with 1.2, which is considered rather poor. [Mozilla for example](https://wiki.mozilla.org/Security/Server_Side_TLS) recommends even for their intermediate configuration to turn them off. In my opinion - feel free to disagree - that configuration should be roughly the default nowadays.

**Comment by slingamn** [comment]
Here's upstream's plan for this: https://github.com/golang/go/issues/45428
