### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by klokocka** [oragono/oragono#186]
I am running Oragono on my server and like it a lot! On the other hand I am a bit frustrated from the lack of documentation on how to both administer and use the server. I am finding a bits and pieces of information here and there, but everything is very scattered and incomplete. 

Small example:
Trying to identify on a nick I have registered
> /msg NickServ IDENTIFY foo password
* NickServ is not yet implemented, sorry! To register an account, check /HELPOP REG

> /HELPOP REG
* Help not found

Some of the key topics are:
* Server installation and configuration
* Implemented commands
* Implemented services

Is it possible to improve the documentation at least on those topics a bit?
I believe that it will make Oragono more approachable for people who are not core developers of the system...

**Comment by DanielOaks** [comment]
Hey @klokocka, thanks for using Oragono! And I'm really sorry about the lack of docs!

I really should come up with a better solution to this. There's a few options I could go with... My main thought is to write something along the lines of a 'manual' file that is included in the docs/ folder that goes through all of the above in a nice, easily-readable way. Once it's written up I can also add it as a page to the website, "Latest Manual (v0.10.0)" or something similar. How's something like that sound?

That HELPOP REG thing is irritating, I definitely agree. I'll improve that error message with the next release. I'm also planning to rewrite a lot of the HELP entries wholesale so just suck less (right now, a lot of them aren't that well-written, and as you mention are mostly for developers of the system).

**Comment by klokocka** [comment]
Hello @DanielOaks for quick reply! I really appreciate your responsiveness!

I have no problem reading documentation in files, e.g. oragano.yaml config file is quite well documented. Even tho for some of the entries I had to test them before I fully understood how exactly they work, overall it helped a lot. So keeping the documentation in the docs/ folder written in MarkDown is absolutely fine for me.

My limitation is that I have basically no prior experience with IRC and IRCD so I am missing a number of basic concepts + not everything working the same as on other IRCD so not easy to to work with it. Will be really good to have some at least basic guideline not to need study source code of the server...

Maybe every time you add/fix a functionality, just writing a brief comments, something similar to the config file, into the docs/ should be enough for the start. Anybody who is really interested in making the server working will have a guideline + can serve as a back bone for someone to write proper documentation later on...

Maybe I can try to help by writing down few things that I already understood about it...

**Comment by DanielOaks** [comment]
No problem, thanks for putting in the issue in the first place! Definitely, I totally agree with the concepts and this server working a little differently than others.

I've got a basic manual done up so I'll keep working on that, then put it into docs/. In addition, as you say I can extend it every time a new feature's added.

I'd be glad for help! Even just letting me know exactly what you've run into trouble with (like the `NickServ IDENTIFY` stuff above) helps me know what to focus on, so feel free to put any sorta information you think would be useful in here, I appreciate it :)

**Comment by DanielOaks** [comment]
Hey @klokocka, do you have any thoughts on something along these lines as an initial manual?

https://github.com/oragono/oragono/blob/master/docs/MANUAL.md

Still lots to go of course, and lots of information to fill out, but that shows how I'm thinking it could work. Thanks again for suggesting this, something we should've started working on a while ago :)

**Comment by klokocka** [comment]
Hello Daniel,

I read your manual very carefully and I like it very much! It contains exactly the information about channels and their management I was looking for!

My few cents to the manual:
1) If you want to grow the manual even further, it might be useful to make it a bit more structure. One thing I see is breaking this one long page into smaller parts/separate pages. maybe by sections?
Something like:
1. - Installation and server management
2. - Configuration
3. - Channel management
etc.

2) Probably in the page about "installation and configuration" will be good to include information from the "INFO.md" file. This like "Rehashing" are very useful for somebody who is administrating the server.

3) The configuration file "oragono.yaml" has some minimal comments, but they doesn't explain everything. It might be useful to explain functionality of each parameter in more details on a separate manual page/section.

**Comment by klokocka** [comment]
I was using Slack in the past and even tho I prefer IRC for its simplicity, power and separation of contexts, I still see few things we can learn from it. Just few basic ideas/questions:

1) The fact that "account names are completely unrelated to nicknames" is maybe good for an open platform as IRC historically is, but not for all possible use cases. E.g. in my case we use Oragono as a 
platform for communication in our company. Will be much easier and less confusing if the "nickname ownership" functionality is implemented. I will definitely use it, even if it is just a configuration option.

2) When we use the Oragono only as a company communication tool, we basically don't want anybody from outside to be able to connect to it. This can be partially prevented by configuring a "password to login 
to the server". Unfortunately this is just a partial solution, because for example if somebody leaves the company, then the only possibility to block his access to the server is changing the server password, 
which has the negative effect that everyone else must also start using the new password. Also if I have a password on the server and a different on my user account, I am not sure how to configure my IRC 
client to login into both (server + SASL) on connecting. Isn't it possible to apply something like "Channel modes" on access to the server itself?

3) Is it possible to record a channel timestamped history on the server and then "replay/load" it a users that were not present/logged in at the moment of conversation? I saw somebody configuring it on some other 
ircd with some more/bot and find it quite useful. Or maybe implementing /history command??

4) As I said I like the separation of contexts, i.e. "programs that do one thing and do it well" and also "programs to handle text streams, because that is a universal interface", but also "programs to work together". Maybe an "interface" to cooperate with other tools, e.g. web GUI, photo/text sharing, webcall service, etc. might be useful feature to have.

**Comment by DanielOaks** [comment]
Ah, lotsacomments and suggestions!

With the manual:

1. I definitely agree with extending and building it out in that way, will split it up into more meaningful sections like you suggest.
2. Yeah, INFO.md was sorta a rough ground for just documenting random bits of info. I'll be transferring everything from there into the manual proper.
3. That makes sense! Can go through it from top to bottom and explain it more in-depth.

With the ideas and questions:

1. Nicknames being unrelated to accounts is just because that's the easiest way for me to implement it.  We are planning to let you choose whether to link account names and nicknames with #169, but no news about when exactly that'll land unfortunately (it's a bit of a difficult feature to implement, we'll get there though).
2. Hmm... it's a tough question. What I could implement is a way to say _"Only let users access the server if they login via SASL beforehand"_, how would something like that sound? Then when you have someone new you can simply disable it, let the new person register and then re-enable the protection or something similar... Honestly, I need to build out NickServ to let opers have more control. Let them create accounts for other users, as well as drop existing accounts. I'll make a new issue to look at this and any more suggestions/etc around it would be appreciated, thanks for bringing it up!
3. Not possible to replay channel history at the moment. For what it's worth, [ZNC](https://github.com/znc/znc/) lets you do so, but it'd be useful to build it into the server itself. I'll look at this more, it's a feature that's useful for company stuff like your network. I'm thinking that it'd be easiest to store+replay things based on accounts and registered channels. I'll come up with some ideas, and we'll see what works for this.
4. We used to have a very rough web API but I ended up ripping it out because web frontends are hard to build. I wouldn't mind looking at re-adding it at some point, but it's not on my radar for now (mostly since maintaining it is difficult). File sharing and calling are useful, and we've been discussing it in the IRCv3 Working Group here https://github.com/ircv3/ircv3-ideas/issues/4 and https://gist.github.com/clokep/f7a07fa9e0bdcfe8cf6a , but no implementations yet. In particular, the WebRTC stuff hasn't been implemented because of message size limits, but the new extended sizes that the `draft/message-tags-0.2` allows helps out a lot with that, so it'd probably be possible to implement something like that with `TAGMSG` (but the channels are still an irritating thing to deal with... we'll work it out though).

Heh, lots of tough-to-implement things. But definitely great ideas, and stuff I'm looking to implement at some point in the future. What can help especially is things like [this comment](https://github.com/oragono/oragono/issues/183#issuecomment-361497584) where the actual commands and method for interacting with the system is defined clearly, helps make it really easy to implement. Thanks again for the suggestions and comments, hopefully this is useful!

**Comment by klokocka** [comment]
Thanks a lot for quick reply and taking my suggestions into account. I am really happy that you plan to implement them!

With the manual:

1), 2), 3) Perfect!

With the ideas and questions:

1) Oh, I didn't know it is a difficult thing. Then no problem, I can live without it, it is just a bit inconvenient...

2) Yes, this will be very nice workaround! :-)

3) Good, looking forward to it. It is quite convenient and common thing nowadays. You have it on every web forum, Facebook, Slack, etc. Even most of the IRC web clients implement it...

4) I agree and think that keeping things KISS is the way to go. Anyway web API are not really necessary. If somebody wants to, then he connects to Oragano as any other IRC client. For example in my case as we find the web access often very useful, I plan to run next to Oragono a IRC web client. I am looking at Mauirc (https://github.com/tulir/mauirc) and I like about it that it is also written in Go so I would be able keep my app stack homogeneous...

5) For the other services (File, Image, Code, Video, WebRTC. etc.): I like that you already thought about those ideas, but my opinion is that the way to go is the KISS, i.e. do one thing and do it well. Rest of the things leave for other services. Why not to just integrate with other services/projects like Dropbox, Pastebin, WebRTC Experiment, etc.? The IRCD (Oragono) will provide only a simple text link and the rest will be handled by a 3rd party service. Might be very simple to implement and transparent for the end user. Some irc web clients already implement something like this (e.g. Mibbit with Pastebin), but having it supported in the server/standard will spread it to everybody...

6) I would like to help with things like comments with actual commands, but as I am new to IRC world, I don't know commands or how things work on other IRCD too much. I will try to study about it, but cannot promise too much...

**Comment by slingamn** [comment]
A lot of this is getting addressed in v0.13.0, in particular:

* Strict nickname reservation
* A SASL-only mode, providing exact control of which users can log into the server
* A `/history` command

I'm going to close this and then make sure the manual reflects the changes.
