### ISSUE TITLE
Flood Control

### ISSUE THREAD

**Issue by eklitzke** [oragono/oragono#189]
Oragono should have some kind of flood control mechanism. This is both to prevent abusive users, but also to protect against users who paste a big buffer without realizing it.

The way this works on every other IRC server I've used:
 * Users can send up to *N* messages in *M* seconds without any rate limiting (e.g. 5 messages within 2 seconds)
 * Once the rate limit is hit, new messages are throttled at some rate (e.g. 1 message per second); this means the server has to maintain a small backlog of messages for throttled users
 * If the user exceeds the max backlog size they're disconnected
 * If the user doesn't exceed the rate limit for some amount of time (e.g. 10 seconds) they get unthrottled until they exceed the rate limit again

**Comment by DanielOaks** [comment]
Hmm, yeah I can definitely agree with this, thanks for making the issue! Some sorta fakelag system which we can disable for opers / chanops in some capacity (as some other ircds do just the same). The disconnecting for backlog size happens right now, it's just a little messy.

**Comment by slingamn** [comment]
With the current implementation, I think we can just sleep the goroutine in between (or even during) commands, and then buffering of user input will ultimately be pushed back to the TCP level. If I'm reading `tcp(7)` correctly, Linux defaults to buffering 87380 bytes?

Should the throttling be for all commands? Or should it be `PRIVMSG` only, or even per-channel?

**Comment by DanielOaks** [comment]
Hmm, the interesting thing is we want to vary how long it sleeps for different commands. For instance, `LIST` is generally pretty intensive, PRIVMSG/NOTICE should be sleep'd longer than other commands, etc. We may also change how much PRIVMSG/NOTICE are sleep'd depending on the priv level of the client in the channel.

It's a weird issue to look at, generally fakelag only kicks in after a few messages in a row or similar. From what I've heard, a fair way is to use a 'penalty' system, where you penalise clients and then if they've got X penalties in the last certain amount of time you kick them into fakelag mode...

Lotsa possible ways to solve it, think it'd be worth mocking out with a diagram before we jump into implementation specifics.

**Comment by DanielOaks** [comment]
Discussion around this:

**\<slingamn\>** dan- : i guess the question is, are there any commands that get to "jump the line" w.r.t. fakelag?
**\<slingamn\>** like, once it kicks in, it seems like the way it works is to delay processing of commands
**\<dan-\>** no way to jump the line, everything still gets executed in the order the client sends it to us, just like a 0.5-1 second delay between each command read during fakelag instead of executing right away
**\<dan-\>** I can imagine something like...
**\<slingamn\>** that makes sense. i think if we do not reorder any commands, any fakelag system will just be functionally equivalent to sleeping the goroutine
**\<dan-\>** no fakelag by standard, almost all the time it's off
**\<slingamn\>** basically it's a state machine that outputs how much time to sleep (typically 0)
**\<dan-\>** as they execute commands a 'penalty' gets counted by some fakelag manager, and if they run over the limit (x penalties in the past y time), then they're fakelag'd for a certain amount of time
**\<dan-\>** if they continue doing big-penalty things, the amount of fakelag time keeps increasing until it hits a ceiling
**\<slingamn\>** sounds about right
**\<dan-\>** and then the value output by that manager is used for sleeping the goroutine, ye

**Comment by slingamn** [comment]
Implemented in #222
