### ISSUE TITLE
config option: allow AUTHENTICATE to bypass PASS

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#199]
Both [pidgin](https://gist.github.com/slingamn/829a8a3e4ebcdf6ef2b9c6de862647e7) and hexchat appear to natively support only a single password field. This means that it's hard or impossible to connect to a server that requires a server password (with `PASS`) and then subsequently authenticate with SASL. (With hexchat, there's a workaround where you can hardcode the SASL PLAIN sequence as "custom commands" to be run after connecting.)

Perhaps it would make sense to add a config option that allows a client that successfully authenticated with `AUTHENTICATE` to skip the `PASS` command? Then these deficient clients could be configured to authenticate with SASL only.

**Comment by slingamn** [comment]
This plan will not work as described because those clients send `USER` and `NICK` before `AUTHENTICATE`, and if they send those commands while unauthorized, we'll disconnect them.

I'm considering a workaround where they're allowed to send `USER` and `NICK`, but they're still considered unregistered until they send either `PASS` or `AUTHENTICATE` within 60 seconds, and if they don't they time out and are disconnected as usual. I *think* the only adverse implication of this is that clients without the password can "squat" nicks, denying others access to them (even though they actually use them)?

**Comment by DanielOaks** [comment]
**\<dan\>** hmm
**\<dan\>** the password should only be checked when the user registration finishes
**\<dan\>** since CAP pauses registration, that works to our advantage
**\<dan\>** what we can do is have a flag where instead of just checking for a successful PASS when reg has completed, check for "successful PASS or SASL login"
**\<dan\>** if either of those are done, then let them in
**\<dan\>** otherwise, we can kill them
**\<dan\>** means we don't need to worry about a pseudo-registered state where they're somewhat registered, but can't do a lot of stuff and etc
