### ISSUE TITLE
Possible duplicate RPL_NAMREPLY (353)

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#207]
On IRC, eskimo mentioned that he was seeing a weird issue where `353` was being returned twice after joining a channel on the testnet. Given that there are only four users on the testnet, this appears to be a server bug.

Test, make sure we can (or can't) repro those results and then fix it if it's a bug on our end.

**Comment by slingamn** [comment]
On irc.darwin.network, we currently have an apparent issue where JOIN doesn't send numerics or a NAMES list.

**Comment by DanielOaks** [comment]
um, that's dodge

**Comment by DanielOaks** [comment]
I'm all over the place this weekend and next week, but when I have some time I'll take a good squiz at it and see what I can find.

**Comment by slingamn** [comment]
Yeah, I'll take a look too. I should have gotten a coredump :-\

**Comment by DanielOaks** [comment]
All good man, we'll work out what's going on with it. Always more to test and fix up

**Comment by slingamn** [comment]
I have some logs with an incomplete picture of what happened. Here are two things I'm fairly sure about:

1. The first indication I had of the incident was a *client-side* ping timeout (Hexchat disconnected with "No ping reply for 90 seconds, disconnecting."). When it attempted to reconnect 10 seconds later, oragono thought the original client was still connected; it finally timed out on the server side ("has quit: (Ping timeout: 2m30s)") 1m16s later.
1. During the incident, clients were able to register, but were invariably disconnected after 2m30s (with the expected message "has quit: (Ping timeout: 2m30s)"). Unfortunately, I'm not sure what specifically was failing in terms of PING/PONG (were the PINGs being sent correctly? were the PONG replies just not being recorded correctly?)

**Comment by slingamn** [comment]
I collected some logs from affected clients. It seems like the JOIN command got at least this far:

https://github.com/oragono/oragono/blob/b211fd35da8ae6f5bec8a81940f5fa8cb5f88a83/irc/channel.go#L405

since the clients were subsequently able to receive PRIVMSG sent to the channel. (The fact that PRIVMSG could be sent to the channel implies that the channel's `stateMutex` was not deadlocked, since you need to acquire its read lock to send a PRIVMSG.)

The response buffer that should have contained the topic and the names output was never sent, so if it was a deadlock, it could have happened anywhere between there and here:

https://github.com/oragono/oragono/blob/b211fd35da8ae6f5bec8a81940f5fa8cb5f88a83/irc/commands.go#L48

**Comment by slingamn** [comment]
The bug on darwin was probably not a deadlock, but this: https://github.com/oragono/oragono/commit/d0ded906d4ac8f91c453f6ee544cc7638365a851

Anyway, the rest of this code has been rewritten a lot so it's unlikely that the original `RPL_NAMREPLY` issue can be reproduced.
