### ISSUE TITLE
feature: `history` implementation

### ISSUE THREAD

**Issue by korovkin** [oragono/oragono#309]
hi there, 
what would be a good place to start in order to implement history logging for channels?
(writing messages into a DB, keep them for a certain retention period, and display them when when `/history` is requested by client) 

i would like to implement such a feature, what would be a good spot to add such an IO operation?

**Comment by korovkin** [comment]
any feedback / guidance would be highly appreciated :)

**Comment by slingamn** [comment]
I'm working on this in #304 :-)

The backend right now does not use a database, instead an in-memory ring buffer (so retention is limited by count, not time).

Open question: what should the syntax of `/history` be? [grove.io](https://grove.io/blog/history-playback-irc.html) has an example, with an implied wire format, but I'm not sure what other people are doing.

**Comment by korovkin** [comment]
awesome, do you need any help ? :)

**Comment by jeanm** [comment]
You’ve probably seen it, but just in case: ircv3/ircv3-specifications#349

**Comment by DanielOaks** [comment]
on this, if we do implement _full_ history logging (as in, intended to last longer than just the past 5-50 messages held in memory), we should support multiple storage methods. even if it's just a choice between either flat-file or into a mongo/sqlite db of some kind. full-go would be much preferred, compiling cgo deps isn't too fun :)

**Comment by DanielOaks** [comment]
and yeye, as mentioned by @jeanm using some standard formats for commands and such would be good... I think to start off, just implementing our own `HistoryServ` bot (same as NS/CS), along with automatic replay of history if it's enabled in the server config, would make sense. and we can always create the standard commands on top of that.

**Comment by slingamn** [comment]
In terms of full, persistent history logging, my personal preference is for external log bots rather than something integrated into the ircd. (I'm open to integrating persistent history later on but it's not a high priority for me.)

@korovkin yeah, I could be interested in some help later on :-) After #304 gets merged, I have to do some follow-up work (I'm going to add support for automatic history replay on channel join, requested by a specific user). Once that's in place, we would still need implementations of both the draft `CHATHISTORY` command as specified above, and also probably of a plain `HISTORY` command (since `CHATHISTORY` seems quite difficult to use manually). We could either split those, or you could do them both.

**Comment by slingamn** [comment]
#344 was the initial deliverable for this. Further work will be on #348.
