### ISSUE TITLE
Secret channels have different semantics to most other ircds

### ISSUE THREAD

**Issue by csmith** [oragono/oragono#380]
On most other IRCds, +p marks a channel as private which hides it from /whois and /list replies, while +s marks a channel as secret which stops /names and /who queries from users not in the channel.

Ora doesn't have +p (which is fine, it's a bit of a weird half-way house), but its +s seems to act like +p on other servers -- i.e., an unprivileged client can do a `NAMES` or `WHO` request against a channel with mode +s and receive a full list of users in the channel on Ora.

The Ora manual documents this behaviour but it's kind of confusing for anyone used to the normal semantics, and I can't see a way to actually suppress NAMES/WHO queries for channels.

**Comment by DanielOaks** [comment]
Yeah `+s` should do everything that the normal `+s` mode does and also everything that the normal `+p` mode does – basically `+s` should just hide a channel everywhere it could possibly be hidden, since +s is the one that regular people actually end up knowing and using. Sounds like we're missing some cases here, will investigate and thanks for the yell!
