### ISSUE TITLE
/msg-like mode for HISTORY command

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#383]
(09:44:28 AM) garrick: shivaram: is there a way to have /quote history msg you instead of dumping scrollback in the channel?

**Comment by bogdomania** [comment]
I support this, running oragono-1.1.0-unreleased, for /history #Channame `<limit>,`
I get the messages in the #Channame window/tab. It is far more easier for the user
to read them, if they get dumped in a separate tab.

I will not open a separate issue, since is still related to /history.  So:

/history #channame `<limit>`    <-    works fine. 
/history me                             <-    doesn't. At all. 

Also, in the help section(messages), can you guys add that `<limit>` is a number? As it is now,
could be mistaken for varchar/alphanumeric.

**Comment by slingamn** [comment]
`history me` will only replay PRIVMSG and NOTICE sent directly to the user --- this case works for me in master.

**Comment by bogdomania** [comment]
So, if **_/history m**e_  only returns pvmsgs & notices, please add some sort of syntax description. Also, while nothing to return ( since no notices / pvmsgs ) should output something like "Nothing to display".

**Comment by slingamn** [comment]
`PRIVMSG HistServ HISTORY #chan 250`?

**Comment by slingamn** [comment]
MVP in #1004
