### ISSUE TITLE
auditorium mode

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#484]
This is coming out of discussion in #ircv3 with the Ripcord developer. Conventional IRC channels are O(n^2) in the number of participants, because of the need to propagate all the JOINs and PARTs. One might think that this is unavoidable, because if n people are talking on a channel then the server has to propagate O(n^2) PRIVMSG's. But actually, channels are unusable if more than 100 or so people are talking at once, so the problem is mostly about JOIN, PART, and NAMES for channels where the number of listeners >> the number of speakers.

Idea: an "announcements" mode for channels that is like `+m` (only privileged users can speak), but which strategically suppresses JOIN, PART and NAMES once the number of users goes over a certain threshold. This would be a replacement for site-wide announcements channels on Slack or Discord.

**Comment by DanielOaks** [comment]
Hmm, some servers have Auditorium mode which is basically this:
https://docs.inspircd.org/3/modules/auditorium/
http://docs.dal.net/docs/modes.html#2.1

**Comment by TheMythPT** [comment]
Although being a third party module of UnrealIRCd: https://gitgud.malvager.net/Wazakindjes/unrealircd_mods#m_auditorium

**Comment by bogdomania** [comment]
I remember this mode being used on ircu(Undernet) on #Opschool, where noone could text, but users could ask questions via a bot, and with !next, the first user in queue was getting +m, so except for the @, only one user at a time was allowed to speak...like a ticketing system. Not sure about case usage except this.

**Comment by bogdomania** [comment]
+v, sorry, not +m, the channel was +m. Sorry, I can't edit from phone.

**Comment by bogdomania** [comment]
+v, sorry, not +m, the channel was +m. Sorry, I can't edit from phone.

**Comment by bogdomania** [comment]
above comment^

> -----------------------------------------

so, except for the +m mode, on channel, since no user is able to speak, until and even after !next is invoked, the user could not see the fully populated userlist on the channel ( only @), like noone else was present on channel, just the @ and the !next given voice user. 
Synth: only @ could see the full users list on the Channel(hundreds, if so), the rest of the users, could only see @ and himself/herself in the userlist, adding the +m, since no one +v and up was able to speak.
I don't know how helpful this is, or even if Auditorium should be implemented, or needed.
I think  +j is more useful on it's own, tbh -> #319

**Comment by scanned** [comment]
Thank you sir dan, ill wait for this enhancement soonest 👍

**Comment by slingamn** [comment]
I have a draft of this lying around that I can revive...

**Comment by slingamn** [comment]
@scanned BTW, my guess about your config syntax issue is that you have tabs in the file (YAML requires the use of spaces, not tabs, for indentation).
