### ISSUE TITLE
Make clone + compile easier

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#53]
Based on #52, decided to spend some time based on getting this down.

From a fresh install of Go, the main thing working against this seems to be the sqlite lib we're using. It's super slow unless you go and actually 'install' it (rather than just getting the source code as you do with everything else).

Evaluate the solution used in #52 vs adding a command line example to the readme going over install + run of this.

**Comment by DanielOaks** [comment]
Getting rid of sqlite has really helped with this.

**Comment by DanielOaks** [comment]
Maybe we should also add oragono as an actual binary to the bin folder, not sure what you need to do or how you need to package things to get go to do that. With something like that we could have, say... `oragono start`, which just runs through the basic setup stuff.

**Comment by enckse** [comment]
I see this is opened and things have changed a lot in the last 1.5 years.

The main README.md is outdated for the make targets due to the use of gorelease and that can be updated. Having just done a few things myself in the project it's still a pain to setup some of the vendoring which is just sort of a go-ism as it is today (mainly as it relates to the packages within this repository itself). None of this is a non-starter for someone new.

I would argue that if the README.md was updated for current build process and just indicated what was required this would be 'resolved". You already (awesomely) release builds for a majority of OSes that one could want and I don't think many people are chasing the latest version rather than devs and we can generally handle it if the steps are known :)

**Comment by DanielOaks** [comment]
Nice, I hope it's a fair bit better than it was at least! Pushed a few changes today which should make it reflect reality. If there's any sorta trouble with the new instructions, feel free to yell and we can edit them up a bit more :)
