### ISSUE TITLE
STS duration sent in plaintext?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#599]
(06:09:07 PM) Alexendoo: lstanley: client must ignore the duration over an insecure connection, rather than should
(06:09:32 PM) lstanley: right, as the docs state
(06:09:54 PM) lstanley: (worth noting that oragono (sp?) sends it over insecure connections, but my client ignores it

Not sure if this is a real issue.

**Comment by DanielOaks** [comment]
Ah, nah this is fine. [The spec](https://ircv3.net/specs/extensions/sts#the-duration-key) has this explicitly stated:

> To enforce an STS persistence policy, servers MUST send this key to securely connected clients. Servers MAY send this key to all clients, but insecurely connected clients MUST ignore it.

Worth noting that the 'MAY' sentence was added during draft phase so that servers wouldn't need to add things like conditional cap values based on whether the client's connected via TLS, ehe. I reckon our current behaviour is all good, but thanks for bringing it up as a possible.
