### ISSUE TITLE
configurable ascii-only mode for identifiers

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#693]
Unchangeable via rehash, requires ascii for nicks/channels/accounts.

**Comment by slingamn** [comment]
Three options:

1. Status quo, with PRECIS casefolding and skeletons
2. Strict, ASCII-only
3. Permissive, allowing emoji

**Comment by DanielOaks** [comment]
It's worth keeping in mind that because emojis can't be folded effectively, a permissive mode that allows them inside identifiers is unsafe (you **will** be able to spoof the identifiers of people using emoji in their identifiers, afaik there's no way to do it safely right now). We don't want to encourage using that mode, so I might suggest a name that notes the danger a bit more and/or warning messages when that mode is enabled.
