### ISSUE TITLE
Blank CAP REQ results in blank CAP ACK

### ISSUE THREAD

**Issue by csmith** [oragono/oragono#835]
I don't think this behaviour is well defined in the capabilities spec, but it seems a bit odd.

If a client sends a blank CAP REQ, i.e. `CAP REQ` or `CAP REQ :`, oragono responds with an empty ACK:

    :irc.server.com CAP * ACK :

I'd expect to get a ERR_NEEDMOREPARAMS back rather than Oragono playing along with the weirdness.

**Comment by DanielOaks** [comment]
This should be brought up through v3 and the correct response should be made clear there. I'm inclined to keep doing this behaviour because if a client somehow stuffs up their cap negotiation during connection reg and ends up requesting no caps, they'll still get the ACK and continue the registration (e.g. they'll still go send CAP END, etc. if we sent ERR_NEEDMOREPARAMS they probably wouldn't know how to handle that and may not complete connection reg)

**Comment by slingamn** [comment]
I tentatively agree with Dan --- Postel's Law suggests keeping this behavior.

**Comment by hhirtz** [comment]
There is technically enough params, the last one is just empty.
