### ISSUE TITLE
support SNI

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#875]
Nearly everyone using multiple domain names should be able to get by with SANs (subject alternative names). But some people might need SNI. This is well-supported in Go:

https://golang.org/pkg/crypto/tls/#Config

but will require some adjustments to our config file format, so I'm not scheduling it for immediate development until someone has a real-world use case.

**Comment by slingamn** [comment]
Watch out for this:

```
    // Note: if there are multiple Certificates, and they don't have the
    // optional field Leaf set, certificate selection will incur a significant
    // per-handshake performance cost.
```

`tls.LoadX509KeyPair` does *not* initialize `Leaf`; it is necessary to call `x509.ParseCertificate` explicitly.

**Comment by Mikaela** [comment]
I have two use cases that may be a bit niche and very minor.

1. I wish to serve VPN/meshnet/mixnet (in this case [Yggdrasil](https://yggdrasil-network.github.io/)) users in plaintext (as there is protocol encryption already) and otherwise direct users to use TLS. How I succeed at this is:
  * listen on `127.0.0.1:6667`, `[::1]:6667` and have STS-only listener on `192.0.2.1:6667`
    * hit problem that STS capable clients will see the STS tag and attempt to reconnect to 6697 and fail certificate validation. Does this also affect Tor?
        * if I understand the [STS specification](https://ircv3.net/specs/extensions/sts) correctly, it's compatible with SNI and allows listing the hostnames where to enable STS thus excluding the VPS.
2. The IRC network I run is currently (simplifiedly) divided on two servers, one is production running Charybdis and another is entirely different system running Oragono. They are in different domains and thus have different certificates. When one day the Charybdis server will shut down and point to Oragono, I wouldn't have to regenerate the currently used certificates to add the new domains and the old domains could be a different certificate.
  * Pitfall: I have no idea how commonly SNI is supported by IRC clients.

Sorry that this came out a bit of a complicated mess, it looked better in my head. I don't know if this/these are (a) scenario(s) worth supporting if there aren't more reasons.

**Comment by Mikaela** [comment]
Another real world use case: we have a team member who believes in having a different certificate for every domain, while I am not sure if it will affect our Oragono deployment.

**Comment by slingamn** [comment]
Let's go ahead and do this in 2.6.
