### ISSUE TITLE
errNickAccountMismatch message is confusing

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#908]
`errNickAccountMismatch` is returned internally for:

1. Attempting to log in post-registration to an always-on account, or to any account that has a preexisting registered client in nick-equals-account mode
2. Attempting to change nickname to something other than your account name, under those same two conditions

The error message is "Your nickname must match your account name; try logging out and logging back in with SASL", which is good advice for the first case but not the second.

**Comment by DanielOaks** [comment]
Whenever possible, if we don't already, we maybe should just force-change the user's nick to the account's nick. Less error messages, more getting on with things. In (1) if we can't change the user's nick because they're already logged-in we could just say so explicitly e.g. `Your nickname must match your account name, and you are already logged in on a different client`. On (2) we should definitely cut all text after the ; and just tell them `Your nickname must match your account name`.

**Comment by slingamn** [comment]
Yeah, we automatically renick when possible, but it's not possible if there's already a registered client with that nick (you can only reattach pre-registration).

**Comment by slingamn** [comment]
Typoed the ticket number, this is open, #911 should have closed #907 :-\
