### ISSUE TITLE
SASL - Where can I configure a server?

### ISSUE THREAD

**Issue by Lerian715** [oragono/oragono#924]
Hi,
I'm trying to enable SASL authentication on my server but I cannot find any option to set a SASL's server IP/domain. Where is it?
I have done everything from https://github.com/oragono/oragono/blob/master/docs/MANUAL.md#sasl-only-mode.

**Comment by DanielOaks** [comment]
Hey there @Lerian715! By default SASL authentication is enabled and advertised to clients, so you don't need to do anything! IRC SASL doesn't require an IP/domain, when clients are configured with the username/password/etc they'll just send it to the server ([this page](https://freenode.net/kb/answer/sasl) has some instructions for setting up SASL with different clients, it's aimed at freenode but should work fine for us as well).

By default account information is stored internally by Oragono when users use the `/CHANSERV REGISTER` command, but if you're looking to integrate with an external authentication mechanism we do provide LDAP configuration in the config file: https://github.com/oragono/oragono/blob/master/oragono.yaml#L446

**Comment by Lerian715** [comment]
Hi, @DanielOaks,
Thanks for your response.
In my case, I have a custom database with API to provide users so my conception was to create a SASL bridge and connect it with Oragnono, that's why I'm asking for this.

You said 
> when clients are configured with the username/password/etc they'll just send it to the server

Ok, but which server? I have configured Oragnono with a manual that I was link in the first post but now I cannot to log in to my server in any way.
Do you have any proposition for this case?

**Comment by slingamn** [comment]
>I have configured Oragnono with a manual that I was link in the first post but now I cannot to log in to my server in any way.

require-sasl is ignored by default from localhost. Can you connect from localhost or an ssh tunnel? Alternately you can temporarily disable require-sasl, then rehash (with SIGHUP) or restart the server.

> In my case, I have a custom database with API to provide users so my conception was to create a SASL bridge and connect it with Oragnono, that's why I'm asking for this.

We don't have code support for something like this yet, but we could probably add it easily. What authentication API does your system expose?

**Comment by Lerian715** [comment]
> We don't have code support for something like this yet, but we could probably add it easily. What authentication API does your system expose?
The principle of authentication would be basically simple - the customer provides login (as the username in IRC) and token (as the password), sends to our API, which classically validates them and returns the answer whether to log in or not.
We would probably be able to write the plugin ourselves, or extend the existing code, so could you direct us where we should "inject" the whole mechanism? We've pre-located: https://github.com/oragono/oragono/blob/bbd8807d65411e7f723aeb7ef67d820fea094a74/irc/accounts.go#L1002 but we're not sure until the end.

**Comment by DanielOaks** [comment]
Hmm, @slingamn is more intimately familiar with the alternative authentication mechanisms these days but yeah you'd probably add it there and do something very similar to the LDAP authentication: https://github.com/oragono/oragono/blob/bbd8807d65411e7f723aeb7ef67d820fea094a74/irc/accounts.go#L1021

What that bit of code does is:

- Checks the authentication details (username/password) with LDAP.
- If LDAP says authentication is **successful** then it tries to load the account information (their IRC-specific details) from Oragono's account store using `am.LoadAccount`.
- If the account information can't be found (because they've never logged into IRC before), then Oragono creates a blank set of account information using `am.SARegister` and loads that account ingo.

It does all the LDAP stuff before `am.checkPassphrase`, because that's the standard internal bcrypt password check that Oragono does with our normal accounts (which is why the LDAP handler returns early if it does find an account).

We tend to like more standardised mechanisms, so if your API supports some authentication protocol that is used by other software as well it shouldn't be a big drama to plug that in.

**Comment by slingamn** [comment]
Belatedly, Dan is exactly right --- you want to mirror the ldap code, where it checks the password and autocreates a local account if necessary.

**Comment by slingamn** [comment]
This is addressed by #1107.
