### ISSUE TITLE
Client ident/username, vHosts & /lusers

### ISSUE THREAD

**Issue by RunBarryRun** [oragono/oragono#972]
1) If the always-on/bouncer option is enabled for your nickname/account and server restarts then your  ident/username (~) is changing to a default by server one. (example- i got an ident of isback@ when i got connected to the server, i then enabled the always-on option  but after a server restart when i reconnected to my bouncer-nickname my ident changed to  ~user@ 

2) idea for VHOSTS the offer list to include vhosts like  $account.oragono or $nickname.oragono and maybe an option to auto assign a vhost of this type upon authentication/login to the account/nickaname. (example -  my username is theflash if i take $account.oragono  then my vhost will be theflash.oragono)

3)An idea for /Lusers command maybe to include line with something like this : i have 15 online(bouncer-users) and 20 offline :) 
Currently offline bouncer/always-on-users are not being included in the total  users

Great work & thank you for this amazing project. Your time and efforts put into this are much appreciated.

**Comment by slingamn** [comment]
Thanks for the report!

re. item 1, I made a note on #819.

Item 2 is interesting. My sense is that the underlying purpose of this feature would be better accomplished in other ways. For example, in the upcoming 2.1 release, we'll have a "nick-equals-account" feature where in addition to strict nickname reservation (anyone using nick `baz` must be logged into account `baz`), the reverse implication holds as well (anyone logged into account `baz` must be using the nick `baz`, via the multiclient feature if necessary). This allows ban/invite/except masks to refer to nicknames directly. If the goal is just to hide IPs by default, then a better approach might be IP cloaking. Thoughts?

The LUSERS suggestion is interesting. It's a little tricky because responses to LUSERS are [more or less standardized](https://modern.ircdocs.horse/#rplluserclient-251). I'll see if there's something useful we can do here.

**Comment by RunBarryRun** [comment]
the idea for the offered vhosts to include  account or nickname is to be different/unique to each user. we have in the offer list the vhost $nickname.loves.oragono  and 2 users baz and faz selected it so we baz.loves.oragono and faz.loves.oragono :)

**Comment by slingamn** [comment]
>the idea for the offered vhosts to include account or nickname is to be different/unique to each user.

That makes sense, but what underlying purpose does that serve? Is it for use with ban masks, ignore rules, etc., or is it just for fun?

**Comment by RunBarryRun** [comment]
> > the idea for the offered vhosts to include account 
> That makes sense, but what underlying purpose does that serve? Is it for use with ban masks, ignore rules, etc., or is it just for fun?

will help with ban masks and avoid mass bans...and yess..will be cool/fun too :) 
currently the offer/take option is available. If more than 2 users select the same vhost and someone gets *!*@host banned from a channel all users using same host will get banned.

**Comment by slingamn** [comment]
>currently the offer/take option is available

This is a good point. Honestly at this point I think the offerlist functionality might just be deprecated in favor of IP cloaking (which is enabled by default in v2.2).

Suppose IP cloaking is enabled, nick-equals-account is enabled, and the offerlist is empty. Is there still any kind of ban that cannot be expressed without stuffing the account name into the username and/or the hostname? My concern is that this information is basically redundant.

**Comment by RunBarryRun** [comment]
Good evening slingam
In reference to the above, since i don't have much experience in go programming i will share my thoughts; maybe will help..
1) Regarding ident/username(~user) on server restart. What if upon nickname/account registration or when  users set the always-on option we save on databese username and realname at current time...Then on a restart we can get those info from database...Regarding the IP if we implement the $account based cloaks this can be easly resolved too...
2) Regarding /lusers to show online bnc users, what if on stats.go file add something like always-on users count or auto-away? or maybe if an always-on user disconnects from season then not to decrement the total or invisible users ?
3) i saw ur latest issue in regards to /ns setusernsme and i totally agree with u..what if we implement a /setident nick and /chgident(affect user who issues) command only for ircops?

Back in good times i wrote my own ircd  on msL :) i now started learning  go...if i find they way on the above, rest assured i will share with u :)
Once again, thank you guys for the time put into this amazing project!!!!

**Comment by slingamn** [comment]
Persistence of the realname is implemented in 2.2.0 (#1065).

I haven't completely made up my mind here, but here's the moderation workflow recommended in 2.2.0:

https://github.com/oragono/oragono/blob/12bcba01cd4d498e5891c590663a463d104a4c9c/docs/MANUAL.md#moderation

In particular, I am not trying to preserve the functionality of the `/kb` command as implemented in some clients (banning `*!user@host`).

**Comment by RunBarryRun** [comment]
Hello and good morning.
I believe i found the solution to the Persistence of the username or hostname or IP or actual anything for always on clients. here it is:

in **accounts.go** add the following code (line 44) you can add as many like hostname or ip

**keyAccountUsername         = "account.username %s" // client username stored as string**

**in line 682 i have added the below code:**

func (am *AccountManager) saveUsername(account string, username string) {
	key := fmt.Sprintf(keyAccountUsername, account)
am.server.store.Update(func(tx *buntdb.Tx) error {
		username, _ = tx.Get(key)
		return nil
	})
	return
}
**// here on server restart i ve chosen to load accountname as username....**

func (am *AccountManager) loadUsername(account string) (name string) {
	key := fmt.Sprintf(keyAccountName, account)
	am.server.store.Update(func(tx *buntdb.Tx) error {
		name, _ = tx.Get(key)
		return nil
	})
	return
}


then in **client.go** file i edited your code to this:

func (server *Server) AddAlwaysOnClient(account ClientAccount, chnames []string, lastSeen map[string]time.Time, uModes modes.Modes, realname string, **username string**) {
	now := time.Now().UTC()
	config := server.Config()
	if lastSeen == nil && account.Settings.AutoreplayMissed {
		lastSeen = map[string]time.Time{"": now}
	}

	client := &Client{
		lastSeen:   lastSeen,
		lastActive: now,
		channels:   make(ChannelSet),
		ctime:      now,
		languages:  server.Languages().Default(),
		server:     server,

		**// TODO figure out how to set these on reattach?**
		**username:    username,**
		**rawHostname: username  + ".bncusers." + server.name,**
		realIP:      utils.IPv4LoopbackAddress,

		alwaysOn: true,
		realname: realname,
	}

The above is the idea to save all info llike IP, username, hostname in the database and then resolve it from there
:)

**Comment by slingamn** [comment]
Thanks for the proposed contribution. (Are you familiar with [git](https://guides.github.com/introduction/git-handbook/)? It's easier to submit proposed changes via pull request, or branches in a repository fork, or even just patches as produced by `git diff` or `git show`.)

Here are  the constraints I see on this problem:

1. I want channel operators to be able to ban an account. (This is currently possible under `force-nick-equals-account`; you ban `accountName!*@*`. This would not be possible if the hostname somehow combined the account name with IP data.)
2. In the scenario where someone is repeatedly connecting from the same IP, or repeatedly registering new accounts (including always-on accounts) from the same IP, I want channel operators to be able to ban the IP. (This is currently possible in the standard configuration: you ban `*!*@cloaked.hostname`. This would not be possible if hostnames of always-on clients were immediately replaced with a hostname derived from the account name, as in your example.)
3. I don't want to create a permanent user-visible link between an account and the IP of their original registration, e.g., by saving the original cloaked hostname in the database and restoring it on server restart. (Granted, the current behavior is weird because the link isn't permanent, but persists for an indefinite period of time, i.e., until the server is restarted.)
4. To the maximum extent possible, I don't want to have to send `CHGHOST` lines to communicate new hostname information for reconnecting clients, because of the potential slowdown. (See also #1221, which would make publishing hostname changes even more expensive and disruptive.) This is an argument against solutions where the cloaked hostname is saved in the database, but then replaced the first time the user reconnects.

The only solution I can see that meets all four constraints is the status quo.

**Comment by slingamn** [comment]
This is partially addressed by #1312.

**Comment by slingamn** [comment]
Given #1312 I think this is a wontfix.
